### ISSUE TITLE
Publish new version supporting esbuild-loader v3

### ISSUE THREAD

**Issue by MichaelMitchell-at** [pocka/storybook-addon-turbo-build#48]
### Description of the feature

ESbuild-loader v3 introduces a [breaking change](https://github.com/esbuild-kit/esbuild-loader/releases/tag/v3.0.0) which is trivial to fix (change `ESBuildMinifyPlugin` to `EsbuildPlugin`).

Dependabot started a PR here, but it needs to fix the compatibility issue.
https://github.com/pocka/storybook-addon-turbo-build/pull/42

### Possible improvements

It would be nice to be able to use it in order to get the downstream ESBuild updates, which are needed to support new JS/TS syntax changes.

### Optimization level

None

**Comment by pocka** [comment]
3a66433be5f2781aedb444275da75e3a9606eff5 (v2.0.0)

**Comment by MichaelMitchell-at** [comment]
Thank you!
