### ISSUE TITLE
"ESBuildPlugin is no longer required for usage" deprecation warning

### ISSUE THREAD

**Issue by IanVS** [pocka/storybook-addon-turbo-build#5]
It seems like the latest versions of esbuild-loader no longer require `ESBuildPlugin`, and it shows a deprecation warning:

```
[esbuild-loader] ESBuildPlugin is no longer required for usage and will be removed in the next major release. Please refer to the docs and release notes for more info.
```

I'll be happy to submit a PR if you'd like.

**Comment by pocka** [comment]
Since we specify `esbuild-loader` as a regular dependency, we can safely remove the plugin once we upgrade the loader to `^v2.10.0`.

**Comment by pocka** [comment]
187274d4c02924e1530573b5f92b1ae268fd4b26

**Comment by ackl** [comment]
Please could you publish 1.0.0-beta.1 which has this change to npm?

**Comment by pocka** [comment]
@ackl 
> Please could you publish 1.0.0-beta.1 which has this change to npm?

It's already there but with a `beta` install tag. 💨 
https://www.npmjs.com/package/storybook-addon-turbo-build/v/1.0.0-beta.1
