### ISSUE TITLE
Does not work out of the box with Storybook 7

### ISSUE THREAD

**Issue by anomiex** [pocka/storybook-addon-turbo-build#50]
### Description of the bug

Attempting to view the built storybook (from `storybook build`) often gives various errors, such as "Property descriptor must be an object, got undefined" or "can't convert undefined to object".

### How to reproduce the bug?

Using the [tutorial environment](https://storybook.js.org/tutorials/intro-to-storybook/react/en/get-started/),

1. `pnpm dlx degit chromaui/intro-storybook-react-template taskbox`
2. `cd taskbox`
3. `rm yarn.lock`
4. `pnpm install`
5. `pnpm dlx storybook upgrade`
6. `pnpm add storybook-addon-turbo-build` and add `"storybook-addon-turbo-build"` to the `plugins` array in `.storybook/main.js`.
7. `pnpm build-storybook`
8. Point a webserver at the built `storybook-static` directory, then load it in a browser.

### Expected behaviour

Storybook works without errors.

### Optimization level

1

### Addon version

1.1.0

### Storybook version

@storybook/react@7.0.4

### Additional contexts

It works if you configure storybook-addon-turbo-build like this instead:
```
               {
                       name: 'storybook-addon-turbo-build',
                       options: {
                               esbuildMinifyOptions: {
                                       target: 'es2018',
                               },
                       },
               },
```
It seems that code injected when targeting the default es2015 breaks with the way Storybook 7 loads the various bundles, globals from different bundles overwrite each other. es2018 is the lowest value that seems to work.

**Comment by pocka** [comment]
Sorry, this addon does not support SB7 (and won't). I'll update README.

Given the performance improvements of Storybook 7 and webpack 5, I believe this addon does not bring enough benefit considering added complexity. If you want to optimise your build performance on SB7+webpack5 project, I recommend you to manually tweak your webpack configuration.

**Comment by anomiex** [comment]
Good to know, thanks!

In case anyone comes here looking for help on that manual tweaking, here's what I did to reproduce the level-1 optimizations:

* Add esbuild-loader (currently at 3.0.1) to the project.
* In `.storybook/main.mjs`,
  * Add `import { EsbuildPlugin } from 'esbuild-loader';` and `import { ProgressPlugin } from 'webpack';` at the top.
  * Set [`webpackFinal`](https://storybook.js.org/docs/react/builders/webpack#override-the-default-configuration) to something like this (or incorporate the code in here into your existing `webpackFinal`):
     ```js
     	webpackFinal: async config => {
     		// Remove ProgressPlugin and source maps in production builds.
     		if ( process.env.NODE_ENV === 'production' ) {
     			config.devtool = false;
     			config.plugins = config.plugins.filter( p => ! ( p instanceof ProgressPlugin ) );
     		}

     		// Use esbuild to minify.
     		config.optimization.minimizer = [
     			new EsbuildPlugin( {
     				target: 'es2018',
     			} ),
     		];

     		return config;
     	}
     ```
